CREATE DATABASE COVID19

CREATE TABLE PACIENTES(
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(150),
	CPF VARCHAR(11),
	IDADE SMALLINT,
	CIDADE VARCHAR (250),
	ESTADO VARCHAR(2),
	SEXO VARCHAR(1),
	ESTADOCIVIL VARCHAR (50),
	COMORBIDADE BIT,
	DATAREGISTRO DATETIME,
	CONSTRAINT PK_Paciente PRIMARY KEY (ID)
)


CREATE TABLE LOGINS(
	ID INT NOT NULL IDENTITY(1,1) ,
	USUARIO VARCHAR(150),
	SENHA VARCHAR(150),
	GRUPO VARCHAR(150),
	CONSTRAINT PK_Login PRIMARY KEY (ID)
)

INSERT INTO LOGINS(USUARIO,SENHA,GRUPO) VALUES('BRUNA', '00102030', 'ADM')
UPDATE PACIENTES SET ESTADO = 'MG'  WHERE ID = 4
DELETE FROM PACIENTES WHERE ID = 4